version: '3'

services:
  prometheus:
    build: ./prometheus
    networks:
      - broker-kafka
    ports:
      - 9090:9090

  grafana:
    image: "grafana/grafana"
    networks:
      - broker-kafka
    ports:
      - 3000:3000

networks:
  broker-kafka:
    driver: bridge

